import "./globals.css";
import Header from "@/app/components/Header/header";
import Footer from "@/app/components/Footer/footer";

export const metadata = {
  title: "CAT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <div className="grid"></div>
          <Header/>
            {children}
            <Footer />
      </body>
    </html>
  );
}
